# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'UsersInfiniteScrolling' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'SDWebImage'
  pod 'Fakery'
  # Pods for UsersInfiniteScrolling

end
